name: Code Format

on:
  push:
    branches:
    - master
  pull_request:
  workflow_dispatch:

jobs:
  fmt:
    name: Check Code Format and Style
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: go fmt
      run: go fmt

    - name: go vet
      run: go vet

    - name: go generate (clang-format)
      run: go generate

    - name: Display missing format changes
      run: git diff --exit-code
